__resultado__ = {
    'subtopico' : str,
    'fecha_verificacion' : str,
    'cant_graficos' : int,
    'cant_graf_errores' : int,
    'graf_errores' : float,
    'cant_datasets_efvos' : int,
    'cant_datasets_decl' : int,
    'datasets_a_verificar' : list,
    'datasets_declarados_no_cargados' : list,
    'datasets_efectivos_no_declarados' : list,
    'cant_variables_verificadas' : int64,
    'cant_variables_no_cargadas' : int64,
    'cant_variables_no_declaradas' : int64,
    'variables_no_cargadas' : list,
    'variables_no_declaradas' : list,
    'cant_scripts_efvos' : int,
    'cant_scripts_decl' : int,
    'scripts_declarados_no_cargados' : list,
    'cant_scripts_declarados_no_cargados' : int,
    'scripts_efectivos_no_declarados' : list,
    'cant_scripts_efectivos_no_declarados' : int,
    'variables_tipo_dato_verificar' : DataFrame,
    'columnas_con_nulos' : dict[str, tuple[str, int]], # [archivo, columna, #filas]
    'insepccion_fuentes' : DataFrame,
    'encoding_delimiter_df' : DataFrame,
    'control_calidad' : dict,
}

